const data = [{"id":1,"fullname":"Marlow Lewington","avatar":"https://robohash.org/velquivoluptas.png?size=50x50&set=set1","university":"Al Fashir University","department":"Product Management"},
{"id":2,"fullname":"Sheffie Burress","avatar":"https://robohash.org/blanditiisvelitquia.png?size=50x50&set=set1","university":"Korea National University of Arts","department":"Research and Development"},
{"id":3,"fullname":"Jeanine Bennion","avatar":"https://robohash.org/aliasquaseos.png?size=50x50&set=set1","university":"Pázmány Péter Catholic University","department":"Services"},
{"id":4,"fullname":"Pincas Sapp","avatar":"https://robohash.org/illumvelmolestiae.png?size=50x50&set=set1","university":"Dublin Institute of Technology","department":"Accounting"},
{"id":5,"fullname":"Torin Lawles","avatar":"https://robohash.org/sapienteabut.png?size=50x50&set=set1","university":"Kwantleen University College","department":"Marketing"},
{"id":6,"fullname":"Stavros Balnaves","avatar":"https://robohash.org/adquiquisquam.png?size=50x50&set=set1","university":"Gurukul University","department":"Services"},
{"id":7,"fullname":"Gabriello Barchrameev","avatar":"https://robohash.org/etcumquerecusandae.png?size=50x50&set=set1","university":"Shaheed Chamran University","department":"Services"},
{"id":8,"fullname":"Dara Packer","avatar":"https://robohash.org/ipsamidneque.png?size=50x50&set=set1","university":"Ateneo de Naga University","department":"Services"},
{"id":9,"fullname":"Dede Lewknor","avatar":"https://robohash.org/eiusipsumerror.png?size=50x50&set=set1","university":"Universidade de Santa Cruz do Sul","department":"Business Development"},
{"id":10,"fullname":"Mimi Huchot","avatar":"https://robohash.org/suntatpraesentium.png?size=50x50&set=set1","university":"International University College of Technology Twintech (IUCTT)","department":"Product Management"},
{"id":11,"fullname":"Anitra Andersen","avatar":"https://robohash.org/debitishicsaepe.png?size=50x50&set=set1","university":"Sauder School of Business","department":"Legal"},
{"id":12,"fullname":"Morgan Moult","avatar":"https://robohash.org/voluptasadut.png?size=50x50&set=set1","university":"Coppin State College","department":"Human Resources"},
{"id":13,"fullname":"Lucie Hurcombe","avatar":"https://robohash.org/illoeumaut.png?size=50x50&set=set1","university":"Technical University of Varna","department":"Business Development"},
{"id":14,"fullname":"Mahmud Snugg","avatar":"https://robohash.org/teneturdebitiset.png?size=50x50&set=set1","university":"Hakodate University","department":"Services"},
{"id":15,"fullname":"Dagmar Reedick","avatar":"https://robohash.org/harumistesit.png?size=50x50&set=set1","university":"University of Aleppo","department":"Business Development"},
{"id":16,"fullname":"Hildagard Lombard","avatar":"https://robohash.org/similiquequamaccusantium.png?size=50x50&set=set1","university":"Université d'Avignon","department":"Research and Development"},
{"id":17,"fullname":"Octavia Mattheis","avatar":"https://robohash.org/utestcorrupti.png?size=50x50&set=set1","university":"Universidad La Gran Colombia","department":"Research and Development"},
{"id":18,"fullname":"Aurora Pischel","avatar":"https://robohash.org/quodutculpa.png?size=50x50&set=set1","university":"Université Mouloud Mammeri de Tizi Ouzou","department":"Support"},
{"id":19,"fullname":"Ruthann Elmore","avatar":"https://robohash.org/etautet.png?size=50x50&set=set1","university":"Ecole Supérieure d'Informatique et de Management","department":"Training"},
{"id":20,"fullname":"Roi Chuney","avatar":"https://robohash.org/accusantiumeosquae.png?size=50x50&set=set1","university":"Islamic Azad University, Fars Science & Research Branch","department":"Services"},
{"id":21,"fullname":"Dylan Clementi","avatar":"https://robohash.org/etaliquamquo.png?size=50x50&set=set1","university":"Rochester College","department":"Training"},
{"id":22,"fullname":"Tamas Druce","avatar":"https://robohash.org/autemcupiditaterepellat.png?size=50x50&set=set1","university":"VBS Purvanchal University","department":"Research and Development"},
{"id":23,"fullname":"Codie Yelland","avatar":"https://robohash.org/animievenietdolores.png?size=50x50&set=set1","university":"University Vitez In Travnik","department":"Research and Development"},
{"id":24,"fullname":"Ross Dunbleton","avatar":"https://robohash.org/quiaquamalias.png?size=50x50&set=set1","university":"Universidad Nacional de Salta","department":"Business Development"},
{"id":25,"fullname":"Jen Jain","avatar":"https://robohash.org/utsapientelibero.png?size=50x50&set=set1","university":"University of Zambia","department":"Marketing"},
{"id":26,"fullname":"Bax Grene","avatar":"https://robohash.org/sintiustoiste.png?size=50x50&set=set1","university":"Texas Wesleyan University","department":"Legal"},
{"id":27,"fullname":"Amity Barstow","avatar":"https://robohash.org/fugadoloraliquid.png?size=50x50&set=set1","university":"Southwestern University School of Law","department":"Human Resources"},
{"id":28,"fullname":"Doretta Blacksland","avatar":"https://robohash.org/illumabquis.png?size=50x50&set=set1","university":"California College San Diego","department":"Business Development"},
{"id":29,"fullname":"Rochette Huxtable","avatar":"https://robohash.org/repellataliasat.png?size=50x50&set=set1","university":"Osaka Women's University","department":"Sales"},
{"id":30,"fullname":"Ollie Hallows","avatar":"https://robohash.org/temporeaccusamusperferendis.png?size=50x50&set=set1","university":"Universidade de Fortaleza","department":"Product Management"},
{"id":31,"fullname":"Kenn Ellwand","avatar":"https://robohash.org/corruptiminimanemo.png?size=50x50&set=set1","university":"University of Houston, Clear Lake","department":"Services"},
{"id":32,"fullname":"Lorene Littrell","avatar":"https://robohash.org/eumdoloromnis.png?size=50x50&set=set1","university":"Kursk State University","department":"Marketing"},
{"id":33,"fullname":"Padraic Carluccio","avatar":"https://robohash.org/teneturreiciendispossimus.png?size=50x50&set=set1","university":"Cleveland State University","department":"Sales"},
{"id":34,"fullname":"Bianka Felix","avatar":"https://robohash.org/culpaeaquenemo.png?size=50x50&set=set1","university":"Universität Osnabrück","department":"Sales"},
{"id":35,"fullname":"Brenden Birdwhistle","avatar":"https://robohash.org/enimetblanditiis.png?size=50x50&set=set1","university":"Indiana Wesleyan University","department":"Sales"},
{"id":36,"fullname":"Esmeralda MacTrustam","avatar":"https://robohash.org/errorlaboreillo.png?size=50x50&set=set1","university":"Karadeniz Technical University","department":"Product Management"},
{"id":37,"fullname":"Merralee Bunten","avatar":"https://robohash.org/inestvoluptatem.png?size=50x50&set=set1","university":"Nizhny Novgorod State University","department":"Human Resources"},
{"id":38,"fullname":"Mannie Weekland","avatar":"https://robohash.org/etquiin.png?size=50x50&set=set1","university":"Oita University","department":"Engineering"},
{"id":39,"fullname":"Andromache Allington","avatar":"https://robohash.org/vitaehiccumque.png?size=50x50&set=set1","university":"Mid-Continent Baptist Bible College","department":"Human Resources"},
{"id":40,"fullname":"Shelagh Banyard","avatar":"https://robohash.org/quirationequos.png?size=50x50&set=set1","university":"Leyte Normal University","department":"Sales"},
{"id":41,"fullname":"Nate Clevely","avatar":"https://robohash.org/sinttemporibusvoluptatem.png?size=50x50&set=set1","university":"Spiru Haret University","department":"Business Development"},
{"id":42,"fullname":"Tara MacDaid","avatar":"https://robohash.org/consequaturutet.png?size=50x50&set=set1","university":"Universidad de Málaga","department":"Business Development"},
{"id":43,"fullname":"Rhianon Elms","avatar":"https://robohash.org/quaeratvoluptascum.png?size=50x50&set=set1","university":"Tula State University","department":"Product Management"},
{"id":44,"fullname":"Cyrus Ramsay","avatar":"https://robohash.org/exidsint.png?size=50x50&set=set1","university":"Hebei University of Science and Technology","department":"Business Development"},
{"id":45,"fullname":"Deedee Pinney","avatar":"https://robohash.org/solutaestquis.png?size=50x50&set=set1","university":"St. Matthews University","department":"Engineering"},
{"id":46,"fullname":"Perry Mitchelhill","avatar":"https://robohash.org/laborepraesentiumneque.png?size=50x50&set=set1","university":"St. John's College New Mexico","department":"Training"},
{"id":47,"fullname":"Lulita Minget","avatar":"https://robohash.org/corruptiiddolorem.png?size=50x50&set=set1","university":"Universidad Autónoma de la Laguna","department":"Research and Development"},
{"id":48,"fullname":"Carney Dearing","avatar":"https://robohash.org/estquisquamqui.png?size=50x50&set=set1","university":"Manhattanville College","department":"Research and Development"},
{"id":49,"fullname":"Perkin Bentjens","avatar":"https://robohash.org/estplaceatculpa.png?size=50x50&set=set1","university":"East China Normal University","department":"Business Development"},
{"id":50,"fullname":"Carson Sendley","avatar":"https://robohash.org/exquodolore.png?size=50x50&set=set1","university":"Universidad International SEK, Santiago","department":"Product Management"},
{"id":51,"fullname":"Quintus Castillo","avatar":"https://robohash.org/aliquidminimanisi.png?size=50x50&set=set1","university":"Hosei University","department":"Human Resources"},
{"id":52,"fullname":"Alvy Bolles","avatar":"https://robohash.org/doloremoptiodeserunt.png?size=50x50&set=set1","university":"Instituto Superior Bissaya Barreto","department":"Engineering"},
{"id":53,"fullname":"Waly De La Salle","avatar":"https://robohash.org/undeperspiciatisest.png?size=50x50&set=set1","university":"Universidad Nacional Experimental Romulo Gallegos","department":"Research and Development"},
{"id":54,"fullname":"Anjanette Bourdon","avatar":"https://robohash.org/quinonfacilis.png?size=50x50&set=set1","university":"Trinity University","department":"Legal"},
{"id":55,"fullname":"Uta Malitrott","avatar":"https://robohash.org/etiddolor.png?size=50x50&set=set1","university":"University of Plymouth","department":"Support"},
{"id":56,"fullname":"Trish Peeke-Vout","avatar":"https://robohash.org/inciduntquodipsam.png?size=50x50&set=set1","university":"Haramaya University","department":"Support"},
{"id":57,"fullname":"Tobie Sullens","avatar":"https://robohash.org/quiquamodit.png?size=50x50&set=set1","university":"Kogi State University","department":"Engineering"},
{"id":58,"fullname":"Tera Fulks","avatar":"https://robohash.org/consequunturminimamagnam.png?size=50x50&set=set1","university":"Institut Supérieur d'Agriculture Lille","department":"Legal"},
{"id":59,"fullname":"Vidovic Bussell","avatar":"https://robohash.org/impeditsapienteet.png?size=50x50&set=set1","university":"Columbus College of Art and Design","department":"Services"},
{"id":60,"fullname":"Karrie Quiney","avatar":"https://robohash.org/sedfugitaut.png?size=50x50&set=set1","university":"Great Lakes University of Kisumu","department":"Training"},
{"id":61,"fullname":"Joyann Streeting","avatar":"https://robohash.org/nihilquaeratmodi.png?size=50x50&set=set1","university":"Stamford University","department":"Legal"},
{"id":62,"fullname":"Andriana Ruppel","avatar":"https://robohash.org/eosexcepturirem.png?size=50x50&set=set1","university":"Brooks Institute of Photography","department":"Engineering"},
{"id":63,"fullname":"Cart Donegan","avatar":"https://robohash.org/rerumvoluptasoccaecati.png?size=50x50&set=set1","university":"Politécnico de Guanajuato","department":"Engineering"},
{"id":64,"fullname":"Ulrick Brammer","avatar":"https://robohash.org/errorbeataenobis.png?size=50x50&set=set1","university":"Western Mindanao State University","department":"Legal"},
{"id":65,"fullname":"Gina Antonucci","avatar":"https://robohash.org/ducimusofficiarerum.png?size=50x50&set=set1","university":"Arizona State University, Downtown Phoenix Campus","department":"Accounting"},
{"id":66,"fullname":"Gerianne O'Keenan","avatar":"https://robohash.org/voluptatibusmagnimagnam.png?size=50x50&set=set1","university":"Azerbaijan National Conservatorie","department":"Training"},
{"id":67,"fullname":"Anne-marie Seller","avatar":"https://robohash.org/iurecumqueest.png?size=50x50&set=set1","university":"Fachhochschulstudiengänge Wels","department":"Human Resources"},
{"id":68,"fullname":"Chaim Bernath","avatar":"https://robohash.org/possimusmaximecupiditate.png?size=50x50&set=set1","university":"University of Florence","department":"Services"},
{"id":69,"fullname":"Mechelle Simeon","avatar":"https://robohash.org/autfugaut.png?size=50x50&set=set1","university":"Fukui Prefectural University","department":"Support"},
{"id":70,"fullname":"Frederico Novelli","avatar":"https://robohash.org/undemodiet.png?size=50x50&set=set1","university":"Tokyo College of Music","department":"Research and Development"},
{"id":71,"fullname":"Hedwiga Inwood","avatar":"https://robohash.org/voluptatumnihilquia.png?size=50x50&set=set1","university":"Universidad Interamericana de Educacion a Distancia de Panama","department":"Human Resources"},
{"id":72,"fullname":"Riordan Curnokk","avatar":"https://robohash.org/totamminusillum.png?size=50x50&set=set1","university":"Omsk State University","department":"Research and Development"},
{"id":73,"fullname":"Tammi Arundell","avatar":"https://robohash.org/cumconsequaturet.png?size=50x50&set=set1","university":"American Conservatory Theater","department":"Marketing"},
{"id":74,"fullname":"Elicia Balderstone","avatar":"https://robohash.org/repudiandaeautvero.png?size=50x50&set=set1","university":"University of Wamia and Masuria in Olsztyn","department":"Business Development"},
{"id":75,"fullname":"Catha Rozenbaum","avatar":"https://robohash.org/officianemonatus.png?size=50x50&set=set1","university":"Odessa National Academy of Food Technologies","department":"Human Resources"},
{"id":76,"fullname":"Britney Ruggier","avatar":"https://robohash.org/culpaetaut.png?size=50x50&set=set1","university":"Benemerita Universidad Autónoma de Puebla","department":"Human Resources"},
{"id":77,"fullname":"Ezekiel Henriquet","avatar":"https://robohash.org/consequunturautvoluptate.png?size=50x50&set=set1","university":"Mary Baldwin College","department":"Legal"},
{"id":78,"fullname":"Granville Pulteneye","avatar":"https://robohash.org/beataesuntrem.png?size=50x50&set=set1","university":"Osaka University of Pharmaceutical Sciences","department":"Accounting"},
{"id":79,"fullname":"Klara Eglese","avatar":"https://robohash.org/omnisvoluptatemcumque.png?size=50x50&set=set1","university":"Gifu University for Education and Languages","department":"Business Development"},
{"id":80,"fullname":"Walliw Netley","avatar":"https://robohash.org/magnamvoluptatemquas.png?size=50x50&set=set1","university":"Seian University of Art & Design","department":"Support"},
{"id":81,"fullname":"Maddi McNutt","avatar":"https://robohash.org/magninonsint.png?size=50x50&set=set1","university":"Indian Institute of Technology, Roorkee","department":"Human Resources"},
{"id":82,"fullname":"Dene Sandiford","avatar":"https://robohash.org/etdolorarchitecto.png?size=50x50&set=set1","university":"University of Maine, Presque Isle","department":"Training"},
{"id":83,"fullname":"Alexis Dillintone","avatar":"https://robohash.org/consequaturautemtempore.png?size=50x50&set=set1","university":"Bard Graduate Center for Studies in the Decorative Arts","department":"Sales"},
{"id":84,"fullname":"Ilario Roskam","avatar":"https://robohash.org/eoseumaspernatur.png?size=50x50&set=set1","university":"Shanghai Ouhua Vocational Technical College","department":"Sales"},
{"id":85,"fullname":"Nessie Szanto","avatar":"https://robohash.org/sequivoluptasex.png?size=50x50&set=set1","university":"British Columbia Open University","department":"Product Management"},
{"id":86,"fullname":"Raymond Aldcorn","avatar":"https://robohash.org/suscipitquasiexcepturi.png?size=50x50&set=set1","university":"Islamic University in Uganda","department":"Research and Development"},
{"id":87,"fullname":"Gustave Bruineman","avatar":"https://robohash.org/rerumeosquia.png?size=50x50&set=set1","university":"Indian Statistical Institute","department":"Marketing"},
{"id":88,"fullname":"Goran Basnett","avatar":"https://robohash.org/itaquerecusandaeminima.png?size=50x50&set=set1","university":"Zetech College","department":"Sales"},
{"id":89,"fullname":"Halsey Cashmore","avatar":"https://robohash.org/quiautveritatis.png?size=50x50&set=set1","university":"Tyumen State University of Gas and Oil","department":"Legal"},
{"id":90,"fullname":"Creigh Buckleigh","avatar":"https://robohash.org/utquibusdamenim.png?size=50x50&set=set1","university":"Dogus University","department":"Sales"},
{"id":91,"fullname":"Cord Acock","avatar":"https://robohash.org/voluptatumpossimussequi.png?size=50x50&set=set1","university":"University of Electro-Communications","department":"Services"},
{"id":92,"fullname":"Cate Wayvill","avatar":"https://robohash.org/possimusfugiatcum.png?size=50x50&set=set1","university":"Bryn Mawr College","department":"Training"},
{"id":93,"fullname":"Cherie Simionescu","avatar":"https://robohash.org/itaqueinducimus.png?size=50x50&set=set1","university":"Merkur Internationale FH Karlsruhe","department":"Business Development"},
{"id":94,"fullname":"Gerti Treneman","avatar":"https://robohash.org/iureinciduntsed.png?size=50x50&set=set1","university":"Iraq University College","department":"Product Management"},
{"id":95,"fullname":"Amye Barthram","avatar":"https://robohash.org/veniamsolutaodio.png?size=50x50&set=set1","university":"University of Essex","department":"Accounting"},
{"id":96,"fullname":"Jarret Didsbury","avatar":"https://robohash.org/consequaturatqui.png?size=50x50&set=set1","university":"Universidad Nacional Experimental de los Llanos Occidentales \"Ezequiel Zamora\"","department":"Sales"},
{"id":97,"fullname":"Tine Sirman","avatar":"https://robohash.org/laudantiumrerumomnis.png?size=50x50&set=set1","university":"Academy of Economics in Katowice","department":"Support"},
{"id":98,"fullname":"Kendall Charter","avatar":"https://robohash.org/rerumeaquaerat.png?size=50x50&set=set1","university":"Evangel University","department":"Human Resources"},
{"id":99,"fullname":"Dorey Bushel","avatar":"https://robohash.org/similiqueatqueprovident.png?size=50x50&set=set1","university":"Molde University College","department":"Business Development"},
{"id":100,"fullname":"Sue Waber","avatar":"https://robohash.org/quiestquos.png?size=50x50&set=set1","university":"COMSATS Institute of Information Technology, Abbottabad","department":"Legal"},
{"id":101,"fullname":"Blisse Bramstom","avatar":"https://robohash.org/estliberoeum.png?size=50x50&set=set1","university":"China University of Mining Technology - Xuzhou","department":"Legal"},
{"id":102,"fullname":"Ammamaria Gornal","avatar":"https://robohash.org/magnisaepesunt.png?size=50x50&set=set1","university":"St. Joseph's College New York","department":"Human Resources"},
{"id":103,"fullname":"Annelise Stillmann","avatar":"https://robohash.org/totamquaseos.png?size=50x50&set=set1","university":"Millikin University","department":"Accounting"},
{"id":104,"fullname":"Arlee Bonifazio","avatar":"https://robohash.org/ametveritatiseaque.png?size=50x50&set=set1","university":"Aikoku Gakuen University","department":"Sales"},
{"id":105,"fullname":"Yurik Millier","avatar":"https://robohash.org/corporisquotempora.png?size=50x50&set=set1","university":"Khulna University","department":"Product Management"},
{"id":106,"fullname":"Irvine Keddy","avatar":"https://robohash.org/delenitiquout.png?size=50x50&set=set1","university":"Babcock University","department":"Marketing"},
{"id":107,"fullname":"Clyve Fulbrook","avatar":"https://robohash.org/voluptatesatquesed.png?size=50x50&set=set1","university":"Amirkabir College of Managmant & Technology","department":"Legal"},
{"id":108,"fullname":"Hieronymus Bartlet","avatar":"https://robohash.org/utarchitectonecessitatibus.png?size=50x50&set=set1","university":"Universidade Federal de Juiz de Fora","department":"Human Resources"},
{"id":109,"fullname":"Micky Pettegree","avatar":"https://robohash.org/namquiamagni.png?size=50x50&set=set1","university":"International Medical University","department":"Marketing"},
{"id":110,"fullname":"Donal Parzis","avatar":"https://robohash.org/itaquedoloresaut.png?size=50x50&set=set1","university":"University of Science & Technology Chittagong","department":"Marketing"},
{"id":111,"fullname":"Prentiss Duffield","avatar":"https://robohash.org/delectusquiaatque.png?size=50x50&set=set1","university":"Islamic Azad University, Bojnourd","department":"Business Development"},
{"id":112,"fullname":"Boyce Biggadyke","avatar":"https://robohash.org/quaeratdictaipsa.png?size=50x50&set=set1","university":"Université de Toamasina","department":"Business Development"},
{"id":113,"fullname":"Brena Smethurst","avatar":"https://robohash.org/atquepariatureum.png?size=50x50&set=set1","university":"Belarussian State Technological University","department":"Marketing"},
{"id":114,"fullname":"Dulcinea Tym","avatar":"https://robohash.org/dictaperferendisdeleniti.png?size=50x50&set=set1","university":"Indian Institute of Technology, Roorkee","department":"Accounting"},
{"id":115,"fullname":"Beryle Brooking","avatar":"https://robohash.org/autexpeditarerum.png?size=50x50&set=set1","university":"Ohka Gakuen University","department":"Support"},
{"id":116,"fullname":"Denny Gonnel","avatar":"https://robohash.org/maioresconsequatura.png?size=50x50&set=set1","university":"Woosuk University","department":"Accounting"},
{"id":117,"fullname":"Colene Brokenshaw","avatar":"https://robohash.org/atquedoloremqueconsequatur.png?size=50x50&set=set1","university":"Curtin University of Technology, Sarawak Campus","department":"Human Resources"},
{"id":118,"fullname":"Gib Bonaire","avatar":"https://robohash.org/doloreseumillum.png?size=50x50&set=set1","university":"University of Aizu","department":"Marketing"},
{"id":119,"fullname":"Constanta Gustus","avatar":"https://robohash.org/officiismagnivel.png?size=50x50&set=set1","university":"University of Massachusetts at Dartmouth","department":"Business Development"},
{"id":120,"fullname":"Alanah Nunson","avatar":"https://robohash.org/autevenietlaudantium.png?size=50x50&set=set1","university":"University of Science and Technology Beijing","department":"Human Resources"},
{"id":121,"fullname":"Perle Freen","avatar":"https://robohash.org/commodirerumillum.png?size=50x50&set=set1","university":"Fondation Universitaire Luxembourgeoise","department":"Product Management"},
{"id":122,"fullname":"Sigismondo Lanchberry","avatar":"https://robohash.org/isteullamvero.png?size=50x50&set=set1","university":"University of California, Merced","department":"Legal"},
{"id":123,"fullname":"Odelia Scullard","avatar":"https://robohash.org/enimtenetursint.png?size=50x50&set=set1","university":"Ecole Supérieure des Sciences Economiques et Commerciales","department":"Services"},
{"id":124,"fullname":"Isidor Heape","avatar":"https://robohash.org/cumsaepetempore.png?size=50x50&set=set1","university":"Universidade Federal Fluminense","department":"Marketing"},
{"id":125,"fullname":"Sidoney Teasell","avatar":"https://robohash.org/remevenietnecessitatibus.png?size=50x50&set=set1","university":"Islamic Azad University, Ahar","department":"Sales"},
{"id":126,"fullname":"Jeni Toffts","avatar":"https://robohash.org/impeditquodnostrum.png?size=50x50&set=set1","university":"University of Art and Design Helsinki","department":"Human Resources"},
{"id":127,"fullname":"Diane-marie Waskett","avatar":"https://robohash.org/quianequedolore.png?size=50x50&set=set1","university":"Bournemouth University","department":"Training"},
{"id":128,"fullname":"Humbert Bodega","avatar":"https://robohash.org/exercitationemquidemasperiores.png?size=50x50&set=set1","university":"South Dakota School of Mines and Technology","department":"Engineering"},
{"id":129,"fullname":"Harcourt Gillett","avatar":"https://robohash.org/doloremqueconsequaturut.png?size=50x50&set=set1","university":"Uzbek State World Languages University","department":"Services"},
{"id":130,"fullname":"Avery Stepto","avatar":"https://robohash.org/remmolestiasenim.png?size=50x50&set=set1","university":"Spring Hill College","department":"Research and Development"},
{"id":131,"fullname":"Annalise Forri","avatar":"https://robohash.org/quisquamvoluptatemrerum.png?size=50x50&set=set1","university":"Moscow Technical University of Informatics and Communication","department":"Research and Development"},
{"id":132,"fullname":"Robinet Bonnin","avatar":"https://robohash.org/idsuscipitet.png?size=50x50&set=set1","university":"Christopher Newport University","department":"Engineering"},
{"id":133,"fullname":"Hillier Puig","avatar":"https://robohash.org/estpossimusqui.png?size=50x50&set=set1","university":"St. John's University","department":"Human Resources"},
{"id":134,"fullname":"Dill Yakov","avatar":"https://robohash.org/velrerumaut.png?size=50x50&set=set1","university":"Ecole Nationale Supérieure Agronomique de Toulouse","department":"Services"},
{"id":135,"fullname":"Garv Bartaloni","avatar":"https://robohash.org/ipsafugiatinventore.png?size=50x50&set=set1","university":"Australian Defence Force Academy","department":"Research and Development"},
{"id":136,"fullname":"Lucky Urian","avatar":"https://robohash.org/asperioresdolorumdeserunt.png?size=50x50&set=set1","university":"Jigjiga University","department":"Research and Development"},
{"id":137,"fullname":"Dana Stocks","avatar":"https://robohash.org/doloremofficiaodio.png?size=50x50&set=set1","university":"Universidad Autónoma de Colombia","department":"Services"},
{"id":138,"fullname":"Marj Misson","avatar":"https://robohash.org/velvoluptasea.png?size=50x50&set=set1","university":"Azerbaijan Toursim Institute","department":"Support"},
{"id":139,"fullname":"Syd McConville","avatar":"https://robohash.org/doloremagnidolor.png?size=50x50&set=set1","university":"ICI University","department":"Services"},
{"id":140,"fullname":"Fedora Tankus","avatar":"https://robohash.org/doloremsolutaut.png?size=50x50&set=set1","university":"Beijing Sport University","department":"Research and Development"},
{"id":141,"fullname":"Berti Jeyes","avatar":"https://robohash.org/consecteturadipiscised.png?size=50x50&set=set1","university":"Universitas Jayabaya","department":"Support"},
{"id":142,"fullname":"Ad Mapletoft","avatar":"https://robohash.org/isteestut.png?size=50x50&set=set1","university":"Pratt Institute","department":"Training"},
{"id":143,"fullname":"Silvester Lerven","avatar":"https://robohash.org/undelaborumillo.png?size=50x50&set=set1","university":"Université de Bouaké","department":"Human Resources"},
{"id":144,"fullname":"Deck Tinmouth","avatar":"https://robohash.org/nesciuntvoluptassint.png?size=50x50&set=set1","university":"The Art Institute of Boston","department":"Marketing"},
{"id":145,"fullname":"Faith Querrard","avatar":"https://robohash.org/nonsaepeharum.png?size=50x50&set=set1","university":"Hanoi University of Science","department":"Business Development"},
{"id":146,"fullname":"Dar Sabattier","avatar":"https://robohash.org/accusamusquibusdamrepellat.png?size=50x50&set=set1","university":"Novosibirsk State Academy of Economics and Mangement","department":"Human Resources"},
{"id":147,"fullname":"Sandy Fullard","avatar":"https://robohash.org/quiavoluptatemvoluptatem.png?size=50x50&set=set1","university":"Montana State University - Billings","department":"Marketing"},
{"id":148,"fullname":"Dorine Skidmore","avatar":"https://robohash.org/rerumquaeitaque.png?size=50x50&set=set1","university":"Brigham Young University","department":"Services"},
{"id":149,"fullname":"Simon Ballchin","avatar":"https://robohash.org/quisquamfugitcommodi.png?size=50x50&set=set1","university":"International University of Travnik","department":"Support"},
{"id":150,"fullname":"Kare Cato","avatar":"https://robohash.org/similiquedoloremqueporro.png?size=50x50&set=set1","university":"University of Szczecin","department":"Human Resources"},
{"id":151,"fullname":"Judon Freddi","avatar":"https://robohash.org/autenimneque.png?size=50x50&set=set1","university":"American InterContinental University - Atlanta","department":"Services"},
{"id":152,"fullname":"Shem Petyakov","avatar":"https://robohash.org/sedfacilisquasi.png?size=50x50&set=set1","university":"American-European School of Management ","department":"Business Development"},
{"id":153,"fullname":"Micki Branchflower","avatar":"https://robohash.org/consecteturetatque.png?size=50x50&set=set1","university":"London School of Hygiene & Tropical Medicine, University of London","department":"Human Resources"},
{"id":154,"fullname":"Cesya Eagle","avatar":"https://robohash.org/quisquamquiaharum.png?size=50x50&set=set1","university":"California School of Professional Psychology - Berkley/Alameda","department":"Training"},
{"id":155,"fullname":"Arin Broadberry","avatar":"https://robohash.org/etcupiditateprovident.png?size=50x50&set=set1","university":"Universidad Panamericana","department":"Business Development"},
{"id":156,"fullname":"Patrice Barthel","avatar":"https://robohash.org/similiqueestvoluptates.png?size=50x50&set=set1","university":"Universidade Castelo Branco","department":"Sales"},
{"id":157,"fullname":"Ameline Prodrick","avatar":"https://robohash.org/nostrumaccusamuscumque.png?size=50x50&set=set1","university":"University of Technology Jamaica","department":"Business Development"},
{"id":158,"fullname":"Angelico Busst","avatar":"https://robohash.org/voluptatemipsaprovident.png?size=50x50&set=set1","university":"University of Peradeniya","department":"Marketing"},
{"id":159,"fullname":"Fulvia Moncrieffe","avatar":"https://robohash.org/utenimvoluptate.png?size=50x50&set=set1","university":"Wesley College","department":"Marketing"},
{"id":160,"fullname":"Zollie Matcham","avatar":"https://robohash.org/liberoatrerum.png?size=50x50&set=set1","university":"Rafsanjan University of Medical Sciences","department":"Engineering"},
{"id":161,"fullname":"Alissa Capey","avatar":"https://robohash.org/etametmolestiae.png?size=50x50&set=set1","university":"Guangdong Radio & TV University","department":"Research and Development"},
{"id":162,"fullname":"Elwin Hurley","avatar":"https://robohash.org/optioconsecteturest.png?size=50x50&set=set1","university":"Christelijke Hogeschool Windesheim","department":"Sales"},
{"id":163,"fullname":"Horten Benedito","avatar":"https://robohash.org/aliquidnonoccaecati.png?size=50x50&set=set1","university":"Mzumbe University (Chuo Kikuu Mzumbe)","department":"Sales"},
{"id":164,"fullname":"Al Collen","avatar":"https://robohash.org/repellatetmagnam.png?size=50x50&set=set1","university":"Tainan National College of the Arts","department":"Product Management"},
{"id":165,"fullname":"Margy Oakwood","avatar":"https://robohash.org/reiciendisinventoreconsequatur.png?size=50x50&set=set1","university":"Chongju University","department":"Human Resources"},
{"id":166,"fullname":"Burton Harler","avatar":"https://robohash.org/laboreistesint.png?size=50x50&set=set1","university":"Institut National Supérieur de Formation Agro-Alimentaire","department":"Support"},
{"id":167,"fullname":"Raphaela Hailes","avatar":"https://robohash.org/iurenullaconsequuntur.png?size=50x50&set=set1","university":"Universidad de San Buenaventura","department":"Engineering"},
{"id":168,"fullname":"Jinny Avrashin","avatar":"https://robohash.org/iureoptiodolor.png?size=50x50&set=set1","university":"University of Wisconsin - Stevens Point","department":"Support"},
{"id":169,"fullname":"Gail Rosenfield","avatar":"https://robohash.org/inciduntasperioresvoluptatum.png?size=50x50&set=set1","university":"École nationale d'administration publique, Université du Québec","department":"Engineering"},
{"id":170,"fullname":"Vanessa Verney","avatar":"https://robohash.org/autrerumincidunt.png?size=50x50&set=set1","university":"Seian University of Art & Design","department":"Human Resources"},
{"id":171,"fullname":"Brandice Flintoff","avatar":"https://robohash.org/velestesse.png?size=50x50&set=set1","university":"Baptist Bible College of Pennsylvania","department":"Sales"},
{"id":172,"fullname":"Wakefield Pawley","avatar":"https://robohash.org/quisquamcumqueeum.png?size=50x50&set=set1","university":"Aomori Public College","department":"Legal"},
{"id":173,"fullname":"Denna Dornan","avatar":"https://robohash.org/cupiditaterepellatvoluptatum.png?size=50x50&set=set1","university":"University of Silesia","department":"Legal"},
{"id":174,"fullname":"Nico Mooreed","avatar":"https://robohash.org/involuptasunde.png?size=50x50&set=set1","university":"University of Manila","department":"Research and Development"},
{"id":175,"fullname":"Renelle Jeary","avatar":"https://robohash.org/blanditiisetab.png?size=50x50&set=set1","university":"Arba Minch University","department":"Services"},
{"id":176,"fullname":"Mikkel Eilhart","avatar":"https://robohash.org/autemplaceatconsequuntur.png?size=50x50&set=set1","university":"Institute of Finance Management","department":"Marketing"},
{"id":177,"fullname":"Retha Griffen","avatar":"https://robohash.org/molestiasreprehenderitdolorem.png?size=50x50&set=set1","university":"Pontificia Universidad Católica del Ecuador","department":"Services"},
{"id":178,"fullname":"Nefen Cussons","avatar":"https://robohash.org/quodvoluptasest.png?size=50x50&set=set1","university":"University of Cebu","department":"Research and Development"},
{"id":179,"fullname":"Irwin Ames","avatar":"https://robohash.org/voluptatemmaximelaboriosam.png?size=50x50&set=set1","university":"Polytechnical University of Kabul","department":"Services"},
{"id":180,"fullname":"Jaimie Aldis","avatar":"https://robohash.org/quamquiquia.png?size=50x50&set=set1","university":"Malekan Payame Nour University","department":"Legal"},
{"id":181,"fullname":"Livy Fyldes","avatar":"https://robohash.org/animitemporibusquis.png?size=50x50&set=set1","university":"Visvesvaraya National Institute of Technology","department":"Sales"},
{"id":182,"fullname":"Jazmin Young","avatar":"https://robohash.org/aetautem.png?size=50x50&set=set1","university":"University of California, Merced","department":"Support"},
{"id":183,"fullname":"Rochette Eusden","avatar":"https://robohash.org/dignissimosreiciendisfugiat.png?size=50x50&set=set1","university":"Kawasaki Medical School","department":"Research and Development"},
{"id":184,"fullname":"Frederique Soreau","avatar":"https://robohash.org/voluptasametaut.png?size=50x50&set=set1","university":"Umaru Musa Yar'Adua University ","department":"Product Management"},
{"id":185,"fullname":"Chiarra Pettinger","avatar":"https://robohash.org/quiettempora.png?size=50x50&set=set1","university":"Sungshin Women's University","department":"Sales"},
{"id":186,"fullname":"Herculie Sprott","avatar":"https://robohash.org/quassitet.png?size=50x50&set=set1","university":"Central University College","department":"Business Development"},
{"id":187,"fullname":"Maribeth Alywin","avatar":"https://robohash.org/excepturioccaecatised.png?size=50x50&set=set1","university":"University of Science & Technology Bannu","department":"Legal"},
{"id":188,"fullname":"Mollee O'Cahey","avatar":"https://robohash.org/ducimusbeataesimilique.png?size=50x50&set=set1","university":"College of Technology at Jazan","department":"Legal"},
{"id":189,"fullname":"Zea Bellfield","avatar":"https://robohash.org/nisimaximequis.png?size=50x50&set=set1","university":" Dedan Kimathi University of Technology","department":"Business Development"},
{"id":190,"fullname":"Artemas Lamping","avatar":"https://robohash.org/quiundesit.png?size=50x50&set=set1","university":"St. Mary College","department":"Human Resources"},
{"id":191,"fullname":"Afton Littlefield","avatar":"https://robohash.org/expeditautiusto.png?size=50x50&set=set1","university":"City University of Hong Kong","department":"Sales"},
{"id":192,"fullname":"Therese Simcoe","avatar":"https://robohash.org/isteconsecteturfacilis.png?size=50x50&set=set1","university":"Université de Metz","department":"Support"},
{"id":193,"fullname":"Yancy Eskriet","avatar":"https://robohash.org/harumidea.png?size=50x50&set=set1","university":"University of Science and Technology Beijing","department":"Human Resources"},
{"id":194,"fullname":"Orelee Goodwell","avatar":"https://robohash.org/ullameiuscommodi.png?size=50x50&set=set1","university":"Universidad del Valle de Guatemala","department":"Marketing"},
{"id":195,"fullname":"Wilow Meddick","avatar":"https://robohash.org/laudantiumdictadolorem.png?size=50x50&set=set1","university":"University of Tulsa","department":"Business Development"},
{"id":196,"fullname":"Rozanne Antognetti","avatar":"https://robohash.org/idsednulla.png?size=50x50&set=set1","university":"Trinity Western University","department":"Services"},
{"id":197,"fullname":"Kriste Iggulden","avatar":"https://robohash.org/consequaturnecessitatibusa.png?size=50x50&set=set1","university":"Huanghe Science & Technology University","department":"Sales"},
{"id":198,"fullname":"Kippy Corringham","avatar":"https://robohash.org/atquererumqui.png?size=50x50&set=set1","university":"Tokyo Institute of Technology","department":"Accounting"},
{"id":199,"fullname":"Felicity Barmby","avatar":"https://robohash.org/voluptatemsaepesed.png?size=50x50&set=set1","university":"Universidad Nacional de la Amazonía Peruana","department":"Accounting"},
{"id":200,"fullname":"Jaynell McKenney","avatar":"https://robohash.org/laudantiumsolutapossimus.png?size=50x50&set=set1","university":"Kakatiya University","department":"Marketing"}]

data.forEach((avatar,)=>{
    const cardList = document.querySelector(".cardList");
    cardList.insertAdjacentHTML(
        "beforeend",
        `
        <div class ="card">
            <div class = "left">
                <div class = "imageBox">
                    <img src = "${v.avatar}" alt="">
                </div>
            </div>
            <div class = "right">
                <div class = "name">${v.fullname}</div>
                <div class = "info">
                    <div class = "university">${university}</div>
                    <div class = "department">${department}</div>
                </div>
            </div>
        </div>
        `
    ),
});